VIA_ENABLE = yes
DIGITIZER_ENABLE = yes
PLOOPY_TOUCHPAD_POC = yes
PLOOPY_MT2_CANARY = yes
PLOOPY_MT2_STREAM = yes
OPT_DEFS += -DPLOOPY_TOUCHPAD_POC -DPLOOPY_MT2_CANARY -DPLOOPY_MT2_STREAM
SRC += pixel_scroll_bridge.c mt2_scroll_poc.c
